In [1]:
%run ./import-data.ipynb

In [2]:
from sklearn.preprocessing import scale

## Scale data

####  mean before scaling

In [3]:
np.mean(stars)

 Mean of the integrated profile                  111.079968
 Standard deviation of the integrated profile     46.549532
 Excess kurtosis of the integrated profile         0.477857
 Skewness of the integrated profile                1.770279
 Mean of the DM-SNR curve                         12.614400
 Standard deviation of the DM-SNR curve           26.326515
 Excess kurtosis of the DM-SNR curve               8.303556
 Skewness of the DM-SNR curve                    104.857709
dtype: float64

#### variance before scaling

In [4]:
np.var(stars)

 Mean of the integrated profile                    658.036325
 Standard deviation of the integrated profile       46.826625
 Excess kurtosis of the integrated profile           1.132117
 Skewness of the integrated profile                 38.041028
 Mean of the DM-SNR curve                          868.603133
 Standard deviation of the DM-SNR curve            379.082006
 Excess kurtosis of the DM-SNR curve                20.303729
 Skewness of the DM-SNR curve                    11344.713243
dtype: float64

####  covariance matrix before scaling

In [5]:
pd.DataFrame(np.cov(stars.T), index=stars.columns, columns=stars.columns)

Mean of the integrated profile  \
 Mean of the integrated profile                                     658.073093   
 Standard deviation of the integrated profile                        96.048736   
 Excess kurtosis of the integrated profile                          -23.853705   
 Skewness of the integrated profile                                -116.892709   
 Mean of the DM-SNR curve                                          -225.943499   
 Standard deviation of the DM-SNR curve                            -153.347450   
 Excess kurtosis of the DM-SNR curve                                 27.087397   
 Skewness of the DM-SNR curve                                       393.557356   

                                                Standard deviation of the integrated profile  \
 Mean of the integrated profile                                                    96.048736   
 Standard deviation of the integrated profile                                      46.829241   
 Excess kurtosis of the integrated profile                                         -3.796792   
 Skewness of the integrated profile                                               -22.783689   
 Mean of the DM-SNR curve                                                           1.385346   
 Standard deviation of the DM-SNR curve                                            -6.346471   
 Excess kurtosis of the DM-SNR curve                                                0.907486   
 Skewness of the DM-SNR curve                                                      20.184296   

                                                Excess kurtosis of the integrated profile  \
 Mean of the integrated profile                                                -23.853705   
 Standard deviation of the integrated profile                                   -3.796792   
 Excess kurtosis of the integrated profile                                       1.132181   
 Skewness of the integrated profile                                              6.206730   
 Mean of the DM-SNR curve                                                       12.994706   
 Standard deviation of the DM-SNR curve                                          8.968178   
 Excess kurtosis of the DM-SNR curve                                            -1.635981   
 Skewness of the DM-SNR curve                                                  -24.309478   

                                                Skewness of the integrated profile  \
 Mean of the integrated profile                                        -116.892709   
 Standard deviation of the integrated profile                           -22.783689   
 Excess kurtosis of the integrated profile                                6.206730   
 Skewness of the integrated profile                                      38.043154   
 Mean of the DM-SNR curve                                                74.906204   
 Standard deviation of the DM-SNR curve                                  49.855321   
 Excess kurtosis of the DM-SNR curve                                     -9.139603   
 Skewness of the DM-SNR curve                                          -134.536441   

                                                Mean of the DM-SNR curve  \
 Mean of the integrated profile                              -225.943499   
 Standard deviation of the integrated profile                   1.385346   
 Excess kurtosis of the integrated profile                     12.994706   
 Skewness of the integrated profile                            74.906204   
 Mean of the DM-SNR curve                                     868.651666   
 Standard deviation of the DM-SNR curve                       457.106323   
 Excess kurtosis of the DM-SNR curve                          -81.805597   
 Skewness of the DM-SNR curve                               -1112.154341   

                                                Standard deviation of the DM-SNR curve  \
 Mean of the integrated profile                         

### Normalising the data

In [6]:
X = stars.values
X_scaled = scale(X)
X_scaled[:2]

array([[ 1.14931702,  1.33483164, -0.66956953, -0.400459  , -0.31944026,
        -0.37062547, -0.07279778, -0.28743812],
       [-0.3341682 ,  1.80226533, -0.01178476, -0.37053549, -0.37110188,
        -0.5889241 ,  0.50442694,  0.21158145]])

#### values after scaling

In [7]:
pd.DataFrame(X_scaled, columns=stars.columns).head()

Mean of the integrated profile  \
0                         1.149317   
1                        -0.334168   
2                        -0.314372   
3                         1.000694   
4                        -0.871402   

    Standard deviation of the integrated profile  \
0                                       1.334832   
1                                       1.802265   
2                                      -1.053322   
3                                       1.553254   
4                                      -0.858879   

    Excess kurtosis of the integrated profile  \
0                                   -0.669570   
1                                   -0.011785   
2                                   -0.145233   
3                                   -0.513409   
4                                    0.115609   

    Skewness of the integrated profile   Mean of the DM-SNR curve  \
0                            -0.400459                  -0.319440   
1                            -0.370535                  -0.371102   
2                            -0.116593                  -0.322107   
3                            -0.390178                  -0.304404   
4                            -0.104866                  -0.388010   

    Standard deviation of the DM-SNR curve  \
0                                -0.370625   
1                                -0.588924   
2                                -0.235328   
3                                -0.275666   
4                                -0.763111   

    Excess kurtosis of the DM-SNR curve   Skewness of the DM-SNR curve  
0                             -0.072798                      -0.287438  
1                              0.504427                       0.211581  
2                             -0.125996                      -0.391373  
3                             -0.312265                      -0.481300  
4                              1.324026                       1.386794

#### mean after scaling

In [8]:
np.round(np.mean(X_scaled, axis=0), decimals=10)

array([-0., -0.,  0.,  0., -0.,  0.,  0.,  0.])

#### variance after scaling

In [9]:
variance = np.var(X_scaled, axis=0)
variance_ratio = variance / np.sum(variance)
print(sum(variance_ratio))
print(variance_ratio)
print(variance)

1.0
[0.125 0.125 0.125 0.125 0.125 0.125 0.125 0.125]
[1. 1. 1. 1. 1. 1. 1. 1.]


#### cov matrix after scaling

In [10]:
C = np.cov(X_scaled.T)
pd.DataFrame(C, columns=stars.columns, index=stars.columns)

Mean of the integrated profile  \
 Mean of the integrated profile                                       1.000056   
 Standard deviation of the integrated profile                         0.547167   
 Excess kurtosis of the integrated profile                           -0.873947   
 Skewness of the integrated profile                                  -0.738816   
 Mean of the DM-SNR curve                                            -0.298858   
 Standard deviation of the DM-SNR curve                              -0.307033   
 Excess kurtosis of the DM-SNR curve                                  0.234344   
 Skewness of the DM-SNR curve                                         0.144041   

                                                Standard deviation of the integrated profile  \
 Mean of the integrated profile                                                     0.547167   
 Standard deviation of the integrated profile                                       1.000056   
 Excess kurtosis of the integrated profile                                         -0.521464   
 Skewness of the integrated profile                                                -0.539823   
 Mean of the DM-SNR curve                                                           0.006869   
 Standard deviation of the DM-SNR curve                                            -0.047634   
 Excess kurtosis of the DM-SNR curve                                                0.029431   
 Skewness of the DM-SNR curve                                                       0.027693   

                                                Excess kurtosis of the integrated profile  \
 Mean of the integrated profile                                                 -0.873947   
 Standard deviation of the integrated profile                                   -0.521464   
 Excess kurtosis of the integrated profile                                       1.000056   
 Skewness of the integrated profile                                              0.945782   
 Mean of the DM-SNR curve                                                        0.414391   
 Standard deviation of the DM-SNR curve                                          0.432904   
 Excess kurtosis of the DM-SNR curve                                            -0.341228   
 Skewness of the DM-SNR curve                                                   -0.214503   

                                                Skewness of the integrated profile  \
 Mean of the integrated profile                                          -0.738816   
 Standard deviation of the integrated profile                            -0.539823   
 Excess kurtosis of the integrated profile                                0.945782   
 Skewness of the integrated profile                                       1.000056   
 Mean of the DM-SNR curve                                                 0.412079   
 Standard deviation of the DM-SNR curve                                   0.415163   
 Excess kurtosis of the DM-SNR curve                                     -0.328862   
 Skewness of the DM-SNR curve                                            -0.204794   

                                                Mean of the DM-SNR curve  \
 Mean of the integrated profile                                -0.298858   
 Standard deviation of the integrated profile                   0.006869   
 Excess kurtosis of the integrated profile                      0.414391   
 Skewness of the integrated profile                             0.412079   
 Mean of the DM-SNR curve                                       1.000056   
 Standard deviation of the DM-SNR curve                         0.796599   
 Excess kurtosis of the DM-SNR curve                           -0.616005   
 Skewness of the DM-SNR curve                                  -0.354289   

                                                Standard deviation of the DM-SNR curve  \
 Mean of the integrated profile                         